### ISSUE TITLE
[Bug] layout seems to be broken

### ISSUE THREAD

**Issue by VerstreuteSeele** [CorellanStoma/Friends-Grid#2]
![image](https://user-images.githubusercontent.com/55334727/133944344-a77df0f5-d339-4077-a236-230aa2da481f.png)

yikes. any ideas?

**Comment by VerstreuteSeele** [comment]
fixed. was a plugin. but will banner support come?

**Comment by CorellanStoma** [comment]
> ~fixed. was a plugin.~ but will banner support come?
> 
> not fixed. the plugin was better friendslist which you claim as supported on your page 

Hi, the support for the banners is from hyblocker, there will probably be a better discord port, but since I can't do JS, I can't do it myself right now.

https://github.com/hyblocker/discord-theme-helper 

Apparently the Better Friend List plugin versions (Powercord / Better Discord) react differently. Currently, I do not know why this is the case.

**Comment by VerstreuteSeele** [comment]
oh well.. hyblocker doesnt support that feature for bd yet so yeah.. guess I will have to wait

**Comment by CorellanStoma** [comment]
> ![image](https://user-images.githubusercontent.com/55334727/133944344-a77df0f5-d339-4077-a236-230aa2da481f.png)
> 
> yikes. any ideas?

I have now a quick hotfix for the better friend list (Better Discord). I I will add it in the next update:

**Hotfix:**
```
.mutualGuilds-s7F2aa {
  flex: 0 0 auto;
  position: absolute !important;
  margin-top: 70px;
  margin-right: 10px;
}
```
![image](https://user-images.githubusercontent.com/58918358/133945374-c79703b1-d9f4-425f-a840-be6e88a84918.png)

**Comment by VerstreuteSeele** [comment]
nice. Didnt fully work for me tho. 
![image](https://user-images.githubusercontent.com/55334727/133945567-6a8b6eae-c8b1-464b-9f44-987d89fcd055.png)

for me just 
```
  .mutualGuilds-s7F2aa {
    flex: 0 0 auto;
}
```
looks pretty solid and solved the issue

![image](https://user-images.githubusercontent.com/55334727/133945577-9fbd9e12-3d42-4ba6-88aa-67282b6eceff.png)

-------

what I just noticed tho is that some mutual guilds dont show for it. very weird

**Comment by lolpowerluke** [comment]
well, he "fixed" it in the last update
![image](https://user-images.githubusercontent.com/47672899/134375932-24dd8b48-6f49-4fd3-a2ed-444f538d8018.png)

**Comment by CorellanStoma** [comment]
> well, he "fixed" it in the last update
> ![image](https://user-images.githubusercontent.com/47672899/134375932-24dd8b48-6f49-4fd3-a2ed-444f538d8018.png)

I forgot a few variables in the last update, this should be fixed now, in my better discord client works everything works now.
Best check if you have the latest version and reload the client once.

![image](https://user-images.githubusercontent.com/58918358/134377278-c1a3c4ea-0f11-4bab-a767-c8c5a9381724.png)

**Comment by lolpowerluke** [comment]
still isnt fixed for me after reloading tho
also, how did you get the usrbg to work there?

**Comment by VerstreuteSeele** [comment]
well. the mutual guild bug is fixed but banners still dont load for me sadly. even with only that theme enabled

**Comment by VerstreuteSeele** [comment]
also for some users mutual guilds still dont show which is weird af
